# docker-compose.yml
version: "3.9"

services:
  my_frontend:
    container_name: frontend
    image: node:lts
    working_dir: /var/www/html/app/
    entrypoint: /bin/bash
    ports:
      - "80:80"
    volumes:
      - ./frontend/:/var/www/html/app
    tty: true
    build:
      context: ./
      dockerfile: Dockerfile
