# docker-compose.yml
version: "3.9"

services:
  vue:
    container_name: vue
    image: node:lts
    working_dir: /var/www/html/app/
    entrypoint: /bin/bash
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    networks:
      my-network:
        aliases:
          - vue-app
    volumes:
      - ./:/var/www/html/app
    tty: true
    env_file:
      - ./.env

networks:
  my-network:
